usuarios = [
    {
        "id": 1,
        "nombre": "Juan",
        "paterno": "Pérez",
        "materno": "Gómez",
        "fecha_nacimiento": "1990-01-01",
        "carnet": "123456",
        "sexo": "M",
    },
    {
        "id": 2,
        "nombre": "María",
        "paterno": "López",
        "materno": "García",
        "fecha_nacimiento": "1992-05-15",
        "carnet": "654321",
        "sexo": "F",
    },
    {
        "id": 3,
        "nombre": "Carlos",
        "paterno": "Martínez",
        "materno": "Rodríguez",
        "fecha_nacimiento": "1985-11-30",
        "carnet": "987654",
        "sexo": "M",
    },
    {
        "id": 4,
        "nombre": "Ana",
        "paterno": "González",
        "materno": "Fernández",
        "fecha_nacimiento": "1998-07-22",
        "carnet": "456789",
        "sexo": "F",
    },
    {
        "id": 5,
        "nombre": "Luis",
        "paterno": "Hernández",
        "materno": "Díaz",
        "fecha_nacimiento": "1993-03-10",
        "carnet": "321654",
        "sexo": "M",
    },
    {
        "id": 6,
        "nombre": "Sofía",
        "paterno": "Torres",
        "materno": "Vargas",
        "fecha_nacimiento": "1991-09-05",
        "carnet": "789123",
        "sexo": "F",
    },
    {
        "id": 7,
        "nombre": "Pedro",
        "paterno": "Ramírez",
        "materno": "Morales",
        "fecha_nacimiento": "1988-12-12",
        "carnet": "159753",
        "sexo": "M",
    },
    {
        "id": 8,
        "nombre": "Lucía",
        "paterno": "Flores",
        "materno": "Ortega",
        "fecha_nacimiento": "1995-04-18",
        "carnet": "357159",
        "sexo": "F",
    },
    {
        "id": 9,
        "nombre": "Jorge",
        "paterno": "Silva",
        "materno": "Reyes",
        "fecha_nacimiento": "1994-08-25",
        "carnet": "753951",
        "sexo": "M",
    },
    {
        "id": 10,
        "nombre": "Elena",
        "paterno": "Mendoza",
        "materno": "Castro",
        "fecha_nacimiento": "1997-06-14",
        "carnet": "852456",
        "sexo": "F",
    },
]